import type { Metadata } from 'next';
import '../globals.css';
import { DM_Serif_Text, Noto_Sans_KR, Noto_Serif_KR } from 'next/font/google';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};
const notoSans = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['400']
});
const dmSerif = DM_Serif_Text({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-dm-serif'
});
const notoSerif = Noto_Serif_KR({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-noto-serif'
});
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.className} ${dmSerif.variable} ${notoSerif.variable}`}>{children}</body>
    </html>
  );
}
