import type { Metadata } from 'next';
import '../globals.css';
import { DM_Serif_Text, Noto_Serif_KR, Nanum_Gothic } from 'next/font/google';
import Script from 'next/script';
const KAKAO_SDK_URL = `//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_MAP_API_KEY}&autoload=false`;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};
const nanumGothic = Nanum_Gothic({
  subsets: ['latin'],
  weight: ['400', '700']
});
const dmSerif = DM_Serif_Text({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-dm-serif'
});
const notoSerif = Noto_Serif_KR({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-noto-serif'
});
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <Script type="text/javascript" src={KAKAO_SDK_URL} strategy="beforeInteractive" />
      </head>
      <body className={`${nanumGothic.className} ${dmSerif.variable} ${notoSerif.variable}`}>{children}</body>
    </html>
  );
}
